### ISSUE TITLE
Доработки навигации по приглашению командной строки

### ISSUE THREAD

**Issue by fluttr** [gl00my/instead-game-archive#3]
В приглашении командной строки не происходит:
- переход в начало строки по нажатию на home
- переход в конец строки по нажатию на end
- удаление символа после курсора по нажатию на delete
- удаление слова перед курсором по нажатию на ctrl+backspace
- удаление слова после курсора по нажатию на ctrl+delete
- перевод курсора на предыдущее слово по нажатию на ctrl+left_arrow
- перевод курсора на следующее слово по нажатию на ctrl+right_arrow

Не уверен, баг ли это движка или игры, но из-за этого поведение навигации по приглашению непривычно и немного некомфортно.

**Comment by hugeping** [comment]
Это относится к https://github.com/instead-hub/metaparser
За это время часть из перечисленного появилось.
